language: android
android:
  components:
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  branches:
    only:
      - develop